theme: minima
title: My Test Project
author: Nika
email: Fellstar321@gmail.com
description: > # My description...

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
